[package]
name = "update-auth-key"
version = "0.1.0"
authors = ["Karl Lam <karl.v.lam@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
chrono = "0.4.6"
serde_json = "1.0.39"
crypto-hash = "0.3.3"
reqwest = "0.9.7"
